name: Deploy no GCP

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - staging
jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write # necessario para o token OIDC do Workload Identity Federation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_PROD_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_PROD_SA_EMAIL }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar Docker para Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Definir variáveis de ambiente
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "SERVICE_NAME=guia-prod" >> $GITHUB_ENV
          else
            echo "BRANCH=staging" >> $GITHUB_ENV
            echo "SERVICE_NAME=guia-staging" >> $GITHUB_ENV
          fi

      - name: Build da Imagem Docker
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ vars.GCP_PROD_PROJECT }}/guia-prod/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Deploy da Imagem Docker
        run: |
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROD_PROJECT }}/guia-prod/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy para o Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROD_PROJECT }}/guia-prod/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
