name: Provisionar Infra (Terraform)

on:
  pull_request:
    branches: [main]
    paths: ["infra/**"]
  push:
    branches: [main]
    paths: ["infra/**"]

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/2077626448/locations/global/workloadIdentityPools/github-actions/providers/github-guia-dblocks
  SERVICE_ACCOUNT: github-actions-ci@dblocks-500317.iam.gserviceaccount.com
  TF_STATE_BUCKET: guia-dblocks-500317-tfstate
  GCP_PROJECT_ID: dblocks-500317

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # necessario para o token OIDC do Workload Identity Federation
    defaults:
      run:
        working-directory: infra/environments/production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.2"

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=environments/production"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          terraform plan \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="service_name=guia-prod" \
            -var="image=us-docker.pkg.dev/cloudrun/container/hello"

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # necessario para o token OIDC do Workload Identity Federation
    defaults:
      run:
        working-directory: infra/environments/production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.2"

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=environments/production"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="service_name=guia-prod" \
            -var="image=us-docker.pkg.dev/cloudrun/container/hello"
